# Generated by Django 5.1.4 on 2025-01-01 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('tag', models.CharField(max_length=255, verbose_name='태그')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('end_at', models.DateField()),
                ('is_closed', models.BooleanField(default=False, help_text='상태')),
                ('access_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='입장코드')),
                ('subtitle', models.CharField(max_length=255, verbose_name='부 제목')),
                ('form_description', models.CharField(help_text='상세 내용', max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'db_table': 'form',
            },
        ),
        migrations.CreateModel(
            name='MultipleAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'multiple_answers',
            },
        ),
        migrations.CreateModel(
            name='OptionsOfQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_number', models.CharField(default=0, max_length=2)),
                ('option_context', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'options_of_questions',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_type', models.CharField(choices=[('단답형', '단답형'), ('장문형', '장문형'), ('체크박스', '체크박스'), ('라디오', '라디오'), ('드롭다운', '드롭다운'), ('범위 선택', '범위 선택'), ('별점', '별점'), ('이미지 선택', '이미지 선택'), ('숫자', '숫자'), ('날짜', '날짜'), ('이메일', '이메일'), ('파일업로드', '파일업로드')], max_length=255)),
                ('question', models.TextField()),
                ('question_order', models.IntegerField()),
                ('is_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'respondent',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='SubjectiveAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
            ],
            options={
                'db_table': 'subjective_answers',
            },
        ),
    ]
