# Generated by Django 5.1.4 on 2025-01-08 01:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('tag', models.CharField(max_length=255, verbose_name='태그')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('end_at', models.DateField()),
                ('is_closed', models.CharField(choices=[('TEMP', 'TEMP'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], help_text='상태', max_length=20)),
                ('access_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='입장코드')),
                ('subtitle', models.CharField(max_length=255, verbose_name='부 제목')),
                ('form_description', models.CharField(help_text='상세 내용', max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('target_count', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('is_bookmark', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'form',
            },
        ),
        migrations.CreateModel(
            name='MultipleAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'multiple_answers',
            },
        ),
        migrations.CreateModel(
            name='OptionsOfQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_number', models.SmallIntegerField(default=0)),
                ('option_context', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'options_of_questions',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_type', models.CharField(choices=[('SHORT_TYPE', 'SHORT_TYPE'), ('LONG_TYPE', 'LONG_TYPE'), ('CHECKBOX_TYPE', 'CHECKBOX_TYPE'), ('RADIO_TYPE', 'RADIO_TYPE'), ('DROPDOWN_TYPE', 'DROPDOWN_TYPE'), ('RANGE_TYPE', 'RANGE_TYPE'), ('STAR_RATING_TYPE', 'STAR_RATING_TYPE'), ('IMAGE_SELECT_TYPE', 'IMAGE_SELECT_TYPE'), ('NUMBER_TYPE', 'NUMBER_TYPE'), ('DATE_TYPE', 'DATE_TYPE'), ('EMAIL_TYPE', 'EMAIL_TYPE'), ('FILE_UPLOAD_TYPE', 'FILE_UPLOAD_TYPE')], max_length=255)),
                ('question', models.TextField()),
                ('question_order', models.IntegerField()),
                ('is_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'respondent',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='SubjectiveAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
            ],
            options={
                'db_table': 'subjective_answers',
            },
        ),
    ]
