# Generated by Django 5.1.4 on 2024-12-30 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multipleanswers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multipleanswers',
            name='options_of_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.optionsofquestions'),
        ),
        migrations.AddField(
            model_name='questions',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
        migrations.AddField(
            model_name='optionsofquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.questions'),
        ),
        migrations.AddField(
            model_name='respondent',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
        migrations.AddField(
            model_name='respondent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statistics',
            name='options_of_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.optionsofquestions'),
        ),
        migrations.AddField(
            model_name='subjectiveanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.questions'),
        ),
        migrations.AddField(
            model_name='subjectiveanswers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
