# Generated by Django 5.1.4 on 2025-01-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_bookmark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='target_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form',
            name='is_closed',
            field=models.CharField(choices=[('TEMP', 'TEMP'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], help_text='상태', max_length=20),
        ),
        migrations.AlterField(
            model_name='questions',
            name='layout_type',
            field=models.CharField(choices=[('SHORT_TYPE', 'SHORT_TYPE'), ('LONG_TYPE', 'LONG_TYPE'), ('CHECKBOX_TYPE', 'CHECKBOX_TYPE'), ('RADIO_TYPE', 'RADIO_TYPE'), ('DROPDOWN_TYPE', 'DROPDOWN_TYPE'), ('RANGE_TYPE', 'RANGE_TYPE'), ('STAR_RATING_TYPE', 'STAR_RATING_TYPE'), ('IMAGE_SELECT_TYPE', 'IMAGE_SELECT_TYPE'), ('NUMBER_TYPE', 'NUMBER_TYPE'), ('DATE_TYPE', 'DATE_TYPE'), ('EMAIL_TYPE', 'EMAIL_TYPE'), ('FILE_UPLOAD_TYPE', 'FILE_UPLOAD_TYPE')], max_length=255),
        ),
    ]
