# Generated by Django 5.1.4 on 2025-01-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_description',
            field=models.CharField(blank=True, help_text='상세 내용', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='태그'),
        ),
    ]
