# Generated by Django 5.1.4 on 2024-12-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
