# Generated by Django 5.1.4 on 2025-01-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_form_is_bookmark_form_is_private_form_target_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipleanswers',
            old_name='options_of_question',
            new_name='options_of_questions',
        ),
    ]
