# Generated by Django 5.1.4 on 2025-01-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_rename_options_of_question_multipleanswers_options_of_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipleanswers',
            old_name='options_of_questions',
            new_name='options_of_question',
        ),
    ]
