# Generated by Django 5.1.4 on 2025-01-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_rename_options_of_questions_multipleanswers_options_of_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionsofquestions',
            name='option_context',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
