# Generated by Django 5.1.4 on 2025-01-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_optionsofquestions_option_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionsofquestions',
            name='option_number',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
