# Generated by Django 5.1.4 on 2024-12-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
