# Generated by Django 5.1.4 on 2024-12-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
